namespace Marina.UI.Models;

public enum ProvinceType
{
    EastAzerbaijan,
    WestAzerbaijan,
    Ardabil,
    Isfahan,
    Alborz,
    Ilam,
    Bushehr,
    Tehran,
    ChaharmahalAndBakhtiari,
    SouthKhorasan,
    RazaviKhorasan,
    NorthKhorasan,
    Khuzestan,
    Zanjan,
    Semnan,
    SistanAndBaluchestan,
    Fars,
    Qazvin,
    Qom,
    Kurdistan,
    Kerman,
    Kermanshah,
    KohgiluyehAndBoyerAhmad,
    Golestan,
    Gilan,
    Lorestan,
    Mazandaran,
    Markazi,
    Hormozgan,
    Hamadan,
    Yazd
}
